/***************************************************************/
/* C-file generated by CC1200 Control Center                   */
/*                                                             */
/*  Generated at x/x/2021  12:26.17                             */
/***************************************************************/
 
#define  IOCFG3             0x00 
#define  IOCFG2             0x01 
#define  IOCFG1             0x02 
#define  IOCFG0             0x03 
#define  SYNC3              0x04 
#define  SYNC2              0x05 
#define  SYNC1              0x06 
#define  SYNC0              0x07 
#define  SYNC_CFG1          0x08 
#define  SYNC_CFG0          0x09 
#define  DEVIATION_M        0x0A 
#define  MODCFG_DEV_E       0x0B 
#define  DCFILT_CFG         0x0C 
#define  PREAMBLE_CFG1      0X0D 
#define  PREAMBLE_CFG0      0x0E 
#define  IQIC               0x0F 
#define  CHAN_BW            0x10 
#define  MDMCFG1            0x11 
#define  MDMCFG0            0x12 
#define  SYMBOL_RATE2       0x13 
#define  SYMBOL_RATE1       0x14 
#define  SYMBOL_RATE0       0x15 
#define  AGC_REF            0x16 
#define  AGC_CS_THR         0x17 
#define  AGC_GAIN_ADJUST    0x18 
#define  AGC_CFG3           0x19 
#define  AGC_CFG2           0x1A 
#define  AGC_CFG1           0x1B 
#define  AGC_CFG0           0x1C 
#define  FIFO_CFG           0X1D 
#define  DEV_ADDR           0x1E 
#define  SETTLING_CFG       0x1F 
#define  FS_CFG             0x20 
#define  WOR_CFG1           0x21 
#define  WOR_CFG0           0x22 
#define  WOR_EVENT0_MSB     0x23 
#define  WOR_EVENT0_LSB     0x24 
#define  RXDCM_TIME         0x25 
#define  PKT_CFG2           0x26
